### ISSUE TITLE
QDnsLookup requires a QCoreApplication

### ISSUE THREAD

**Issue by misa3l** [qxmpp-project/qxmpp#38] opened 2015-02-10 03:25 UTC
Hi... 
after spending days trying to compile qxmpp achieve that objective. and so static compiled executable but run it gives me the following error:

QDnsLookup requires a QCoreApplication

Image Error:

http://picpaste.com/qxmpperror-Nung87qj.jpg

PD: Other Cap..

http://picpaste.com/qxmpperror2-tPVEI9FC.jpg

**Comment by jlaine** [comment] 2015-02-19 05:34
Duplicate of #24

**Closed by jlaine** 2015-02-19 05:34 UTC
