### ISSUE TITLE
connecting to a localhost

### ISSUE THREAD

**Issue by Luis-Abreu** [qxmpp-project/qxmpp#48] opened 2015-04-06 13:34 UTC
I'm trying to connect to my localhost ejabberd server.
This is my code:

#include <iostream>
#include <pqxx/pqxx>
#include <QCoreApplication>

#include "qxmpp/QXmppClient.h"
#include "qxmpp/QXmppLogger.h"

int main(int argc, char *argv[])
{
    QCoreApplication app(argc, argv);

    QXmppClient client;
    client.logger()->setLoggingType(QXmppLogger::StdoutLogging);

    // For jabber
    // client.connectToServer("username@jabber.org", "passwd");

    // For google talk
    // client.connectToServer("username@gmail.com", "passwd");

    client.connectToServer("teste@localhost", "teste");

    return app.exec();
}

this is what I get in the terminal:

qt.network.ssl: QSslSocket: cannot resolve SSLv2_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv2_server_method
Mon Apr 6 14:33:51 2015 DEBUG Looking up server for domain localhost
Press <RETURN> to close this window...

It just gets stuck there.
Help? :(

**Comment by jlaine** [comment] 2015-06-03 18:27
Does connecting to a public server work? Without more information all I can say is "the problem is most likely in your local setup"

**Comment by Thomas-Lerman** [comment] 2015-08-14 22:13
I ran into a similar issue and found a couple of things.
1) I tried two XMPP servers and they required a domain name, such as something.com. If a connecting client does not match within the XML, the server rejects it. So, you might try setting up the server to accept localhost, if it will.
2) qxmpp does not allow (that I have found yet) the domain name (something.com) to be something different than the connect server (localhost). So, I had to make changes (see issue #67) to the code to get that to work. I tested it out, including for a localhost connect server, and it worked.
I hope this helps in some way.

**Comment by jlaine** [comment] 2015-08-14 22:53
Thomas as explained in #67 your issue is unrelated.

**Comment by Thomas-Lerman** [comment] 2015-08-15 05:32
Probably right, I just was thinking I got it working (new code) with something like the following:

QXmppConfiguration config;
config.setJid("foo@something.com");
config.setPassword("super_secret");
config.setHost("localhost");
client.connectToServer(config);

Once the XMPP server was set up to accept something.com. However, reading the original post seems to talk about:
qt.network.ssl: QSslSocket: cannot resolve SSLv2_client_method
or server_method. That is different than what I was seeing, so maybe SSL problems???

**Comment by jlaine** [comment] 2016-09-08 18:46
No feedback in over a year, closing

**Closed by jlaine** 2016-09-08 18:46 UTC
